config/routes.rb
Dchack::Application.routes.draw do
  resources :demos

  devise_for :users

  resources :homes

  resources :posts

  root :to => 'homes#index'

end

app/models/demo.rb
class Demo < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @demos }
    end
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
    @demo = Demo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @demo }
    end
  end

  # GET /demos/new
  # GET /demos/new.json
  def new
    @demo = Demo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @demo }
    end
  end

  # GET /demos/1/edit
  def edit
    @demo = Demo.find(params[:id])
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(params[:demo])

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render json: @demo, status: :created, location: @demo }
      else
        format.html { render action: "new" }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /demos/1
  # PUT /demos/1.json
  def update
    @demo = Demo.find(params[:id])

    respond_to do |format|
      if @demo.update_attributes(params[:demo])
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo = Demo.find(params[:id])
    @demo.destroy

    respond_to do |format|
      format.html { redirect_to demos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing demo</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
    <div class="edit"></div>
      <header id="blog-header">
          <h2>VENICE CANALS</h2>
          <h3>Posted On February 1, 2013 By Olivia</h3>
          <div class="pull-right">
            <div class="edit-btn btn" id="edit-btn">Edit</div>
            <div class="done-btn btn" id="done-btn">Done</div>
          </div>
      </header>
      <section class="body-wrapper">
          <div class="toolbar toolbar-hide" id="toolbar">
            <ul>
              <li class="tool" id="text"></li>
              <li class="tool" id="color"></li>
              <li class="tool" id="image"></li>
              <li class="tool" id="audio"></li>
              <li class="tool" id="video"></li>
            </ul>
          </div>
          <div class="body">
              <div class="layouts_grid" id="layouts_grid">
                <ul>
                  <li class="layout_block" data-id="3" data-row="1" data-col="1" data-sizex="14" data-sizey="8" style="background-image: url(<%= image_path('ex1.jpg') %>);"></li>
                   <li class="layout_block" data-id="3" data-row="2" data-col="1" data-sizex="14" data-sizey="8" style="background-image: url(<%= image_path('img_2.jpg') %>);">
                  </li>
                  <li class="layout_block" data-id="3" data-row="2" data-col="1" data-sizex="14" data-sizey="8" style="background-image: url(<%= image_path('img_5.jpg') %>);"></li>

                  <li class="layout_block text" data-id="13" data-row="13" data-col="1" data-sizex="8" data-sizey="6">
                    <p>I took advantage of an unseasonably warm day in <a href="https://en.wikipedia.org/wiki/Venice">Venice</a> to wear out this box tee from one of my favorite New Zealand labels, <a href="http://www.salasai.com/">Salasai</a>. I love shapeless things like this one, even if it tends to be unflattering on my boy like figure. Paired it with my Isabel Rio sandals which have officially become my most versatile purchase up to date, and a glossy red lip to show that I am a girl, after all. On a good day, the Venice Beach canals are a great tourist distraction from the wackiness of the Boardwalk.</p>
                    <p>My best tip for any visitor spending the day on the West Side is to book a reservation at Gjelina’s, take a stroll through <a href="http://www.abbotkinneyonline.com/">Abbot Kinney</a>, stop by Satine, and locate the second rate version of what was inspired by the original Venice Canals. Once you move past the travel recommendations of tourist traps, you can really appreciate what the locals living in Los Angeles are all about. </p>
                    <p>
                      Example photos and blog entry from <a href="http://lusttforlife.com/" title="Lustt For Life">http://lusttforlife.com/</a>.<p>
                  </li>
                  <li id="image-2" class="layout_block" data-id="12" data-row="13" data-col="1" data-sizex="4" data-sizey="4" style="background-image: url(<%= image_path('img_4.jpg') %>);">
                  </li>
                  <li class="layout_block text" id="text-2" data-id="7" data-row="5" data-col="1" data-sizex="6" data-sizey="4">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit modi debitis dolorem repellendus ipsam ratione reprehenderit harum impedit vero praesentium adipisci architecto rem necessitatibus? Voluptas non odio earum eveniet rerum. Est quidem et doloremque a quod unde deserunt omnis culpa. </p>
                    <p>Consectetur adipisicing elit. Ratione porro fuga officiis architecto doloremque dignissimos odio illum.
                    <br />
                    Consectetur adipisicing elit. Ratione porro fuga officiis architecto doloremque dignissimos odio illum.
                    </p>
                  </li>
                </ul>
                <div class="divider"></div>
              </div>
          </div>
      </section>

app/views/demos/new.html.erb
<h1>New demo</h1>

<%= render 'form' %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
        <header>
            <div class="wrapper">
                <a href="/"><h1><span>Banana</span>Plate</h1></a>
                <nav>
                    <% if user_signed_in? %>
                        <a href="#" class="current-user">Username</a>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <% else %>
                        <%= link_to('Login', new_user_session_path, :class => "btn")  %>
                    <% end %>
                </nav>
            </div>
        </header>
        <!-- / header -->

        <section class="hero">
            <article>
                <h2>A fresh new way to fashion blog</h2>
                <p>A publishing platform built for fashion bloggers &amp; designers</p>
                <a href="/posts" class="btn">Try the demo</a>
            </article>
        </section>
        <!-- / hero -->

        <section class="slider">
            <div class="flexslider">
                <div class="flex-viewport">
                    <ul class="slides" style="width: 1000%; -webkit-transition: 0s; -webkit-transform: translate3d(-1146px, 0, 0);">
                        <li class="clone" style="width: 1146px; float: left; display: block;">
                            <article>
                                <p>100% tailored to your needs</p>
                                <%= image_tag("ui.png", :alt => "rss feed") %>
                            </article>
                        </li>
                        <li class="flex-active-slide" style="width: 1146px; float: left; display: block;">
                            <article>
                                <p>Designed for your growth</p>
                                <div class="mask">
                                    <video autoplay="autoplay" loop="loop">
                                        <source src="http://dl.dropbox.com/u/40717613/grow.mp4" type="video/mp4">
                                        Your browser does not support the video tag.
                                    </video>
                                </div>
                            </article>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <!-- / slider -->

        <section class="create">
            <article>
                <div class="wrapper">
                    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                        <%= devise_error_messages! %>

                        <div class="step step-1">
                            <p>bananaplate.com/</p>
                            <%= f.text_field :username, :class => 'accountName' %>
                            <div class="submit-btn" id="sub-1">
                                <%= image_tag("btn-arrow.svg", :alt => "rss feed") %>
                            </div>
                        </div>
                        <div class="step step-2">
                            <p>E-mail address:</p>
                            <%= f.email_field :email, :class => 'accountName' %>
                            <div class="submit-btn" id="sub-2">
                                <%= image_tag("btn-arrow.svg", :alt => "rss feed") %>
                            </div>
                        </div>
                        <div class="step step-3">
                            <p>Create a password:</p>
                            <%= f.password_field :password, :class => 'accountName' %>
                            <a href="/posts" title=""><div class="submit-btn" id="sub-3">
                                <%= image_tag("btn-arrow.svg", :alt => "rss feed") %>
                            </div></a>
                        </div>
                    <% end %>
                </div>
            </article>
        </section>
        <!-- / registration -->

        <footer>
            <article>
                <p>BananaPlate <span>&mdash;</span> Get ripe. Stay fresh.</p>
            </article>
        </footer>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html lang="en">
	<!--
		ENSO - A minimal HTML5 boilerplate
		www.spiegelma.de
	-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title>BananaPlate &mdash; Get ripe now</title>

		<meta name="robots" content="index, follow">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content=" &mdash; A platform for the new fashion blogger.">
		<meta name="keywords" content="bananaplate fashion blog bloggin design shop">
		<meta name="author" content="BananaPlate Team">

		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800,300' rel='stylesheet' type='text/css'>

		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

		<%= javascript_include_tag "application" %>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
    <div class="edit"></div>
      <header id="blog-header">
          <input type="text" class="h2" value="VENICE CANALS"></input>
          <input type="text" class="h3" value="Posted On February 1, 2013 By Olivia"></input>
          <div class="pull-right">
            <div class="edit-btn btn" id="edit-btn">Edit</div>
            <div class="done-btn btn" id="done-btn">Done</div>
          </div>
      </header>
      <section class="body-wrapper">
          <div class="toolbar toolbar-hide" id="toolbar">
            <ul>
              <li class="tool" id="text"></li>
              <li class="tool" id="color"></li>
              <li class="tool" id="image"></li>
              <li class="tool" id="audio"></li>
              <li class="tool" id="video"></li>
            </ul>
          </div>
          <div class="body">
              <div class="layouts_grid" id="layouts_grid">
                <ul>
                  <li class="layout_block" data-id="3" data-row="1" data-col="1" data-sizex="14" data-sizey="8" style="background-image: url(<%= image_path('ex1.jpg') %>);"></li>
                   <li class="layout_block" data-id="3" data-row="2" data-col="1" data-sizex="14" data-sizey="8" style="background-image: url(<%= image_path('img_2.jpg') %>);">
                  </li>
                  <li class="layout_block" data-id="3" data-row="2" data-col="1" data-sizex="14" data-sizey="8" style="background-image: url(<%= image_path('img_5.jpg') %>);"></li>

                  <li class="layout_block text" data-id="13" data-row="13" data-col="1" data-sizex="8" data-sizey="6">
                    <p>I took advantage of an unseasonably warm day in <a href="https://en.wikipedia.org/wiki/Venice">Venice</a> to wear out this box tee from one of my favorite New Zealand labels, <a href="http://www.salasai.com/">Salasai</a>. I love shapeless things like this one, even if it tends to be unflattering on my boy like figure. Paired it with my Isabel Rio sandals which have officially become my most versatile purchase up to date, and a glossy red lip to show that I am a girl, after all. On a good day, the Venice Beach canals are a great tourist distraction from the wackiness of the Boardwalk.</p>
                    <p>My best tip for any visitor spending the day on the West Side is to book a reservation at Gjelina’s, take a stroll through <a href="http://www.abbotkinneyonline.com/">Abbot Kinney</a>, stop by Satine, and locate the second rate version of what was inspired by the original Venice Canals. Once you move past the travel recommendations of tourist traps, you can really appreciate what the locals living in Los Angeles are all about. </p>
                    <p>
                      Example photos and blog entry from <a href="http://lusttforlife.com/" title="Lustt For Life">http://lusttforlife.com/</a>.<p>
                  </li>
                  <li id="image-2" class="layout_block" data-id="12" data-row="13" data-col="1" data-sizex="4" data-sizey="4" style="background-image: url(<%= image_path('img_4.jpg') %>);">
                  </li>
                  <li class="layout_block text" id="text-2" data-id="7" data-row="5" data-col="1" data-sizex="6" data-sizey="4">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit modi debitis dolorem repellendus ipsam ratione reprehenderit harum impedit vero praesentium adipisci architecto rem necessitatibus? Voluptas non odio earum eveniet rerum. Est quidem et doloremque a quod unde deserunt omnis culpa. </p>
                    <p>Consectetur adipisicing elit. Ratione porro fuga officiis architecto doloremque dignissimos odio illum.
                    <br />
                    Consectetur adipisicing elit. Ratione porro fuga officiis architecto doloremque dignissimos odio illum.
                    </p>
                  </li>
                </ul>
                <div class="divider"></div>
              </div>
          </div>
      </section>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/user/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>